sudo: required
dist: trusty
language: csharp
dotnet: 2.1.302
mono: none

stages:
  - compile & unit test
  - test

env:
  - CONFIGURATION=Release NOTHREADS=10 SECURITY=OFF
  - CONFIGURATION=Release NOTHREADS=10 SECURITY=SSL
  - CONFIGURATION=Release NOTHREADS=10 SECURITY=TLS
  - CONFIGURATION=Release NOTHREADS=20 SECURITY=OFF
  - CONFIGURATION=Release NOTHREADS=20 SECURITY=SSL
  - CONFIGURATION=Release NOTHREADS=20 SECURITY=TLS
  - CONFIGURATION=Release NOTHREADS=50 SECURITY=OFF
  - CONFIGURATION=Release NOTHREADS=50 SECURITY=SSL
  - CONFIGURATION=Release NOTHREADS=50 SECURITY=TLS
  - CONFIGURATION=Debug NOTHREADS=50 SECURITY=OFF
  - CONFIGURATION=Debug NOTHREADS=50 SECURITY=SSL
  - CONFIGURATION=Debug NOTHREADS=50 SECURITY=TLS

addons:
  apt:
    packages:
    - ldap-utils
    - gnutls-bin
    - ssl-cert
    - slapd

before_script:
  - whoami
  - mkdir /tmp/slapd
  # start setup ssl
  # prepare folders
  - mkdir -p /tmp/ssl/private
  - mkdir -p /tmp/ssl/certs
  # generate certs/keys
  - sudo certtool -p --outfile /tmp/ssl/private/ca_server.key
  - sudo certtool -s --load-privkey /tmp/ssl/private/ca_server.key --template test/conf/cert_template.conf --outfile /tmp/ssl/certs/ca_server.pem
  - sudo certtool -p --sec-param low --outfile /tmp/ssl/private/ldap_server.key
  - sudo certtool -c --load-privkey /tmp/ssl/private/ldap_server.key --load-ca-certificate /tmp/ssl/certs/ca_server.pem --load-ca-privkey /tmp/ssl/private/ca_server.key --template test/conf/cert_template.conf --outfile /tmp/ssl/certs/ldap_server.pem
  # permissions
  - sudo usermod -aG ssl-cert travis
  - sudo chown travis:ssl-cert /tmp/ssl/private/ldap_server.key /tmp/ssl/certs/ldap_server.pem /tmp/ssl/certs/ca_server.pem
  - sudo chmod 640 /tmp/ssl/private/ldap_server.key /tmp/ssl/certs/ldap_server.pem /tmp/ssl/certs/ca_server.pem
  # end setup ssl
  # start ssl
  - slapd -f test/conf/slapd.conf -h "ldap://localhost:4389 ldaps://localhost:4636" &
  # give openldap enough time to start
  - sleep 5
  # test to see that is running
  - ldapwhoami -H ldap://localhost:4389 -D "cn=root,dc=example,dc=com" -w password 
  - ldapadd -h localhost:4389 -D cn=root,dc=example,dc=com -w password -f test/conf/baseDn.ldif

jobs:
  include:
    - stage: compile & unit test
      env:
      - CONFIGURATION=Release
      script:
      - dotnet restore
      - dotnet build --configuration $CONFIGURATION
      - export TRANSPORT_SECURITY=OFF; dotnet test --configuration $CONFIGURATION test/Novell.Directory.Ldap.NETStandard.FunctionalTests/Novell.Directory.Ldap.NETStandard.FunctionalTests.csproj
      - export TRANSPORT_SECURITY=SSL; dotnet test --configuration $CONFIGURATION test/Novell.Directory.Ldap.NETStandard.FunctionalTests/Novell.Directory.Ldap.NETStandard.FunctionalTests.csproj
      - export TRANSPORT_SECURITY=TLS; dotnet test --configuration $CONFIGURATION test/Novell.Directory.Ldap.NETStandard.FunctionalTests/Novell.Directory.Ldap.NETStandard.FunctionalTests.csproj

script:
  - dotnet restore
  - dotnet build --configuration $CONFIGURATION
  - export TRANSPORT_SECURITY=$SECURITY; dotnet run --configuration $CONFIGURATION --project test/Novell.Directory.Ldap.NETStandard.StressTests/Novell.Directory.Ldap.NETStandard.StressTests.csproj $NOTHREADS 45