sudo: required
dist: trusty

before_install:
  - sudo sh -c 'echo "deb [arch=amd64] http://apt-mo.trafficmanager.net/repos/dotnet/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
  - sudo apt-get update
  - sudo apt-get install -y dotnet-nightly

script:
  - cd Novell.Directory.Ldap.NETStandard
  - dotnet restore
  - dotnet build